### ISSUE TITLE
Sharing of Notes is not working 

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/KeepIt#1]
The share feature is not working.

**Comment by RohitLakra299** [comment]
Hi @aritra-tech , I would like to work on this issue. Could you assign this to me.

**Comment by aritra-tech** [comment]
Yeah sure

**Comment by RohitLakra299** [comment]
@aritra-tech currently share feature is only sharing title of the note, You want to share title + note right ?

**Comment by aritra-tech** [comment]
> @aritra-tech currently share feature is only sharing title of the note, You want to share title + note right ?

Yeah yeh both the title and the notes
