### ISSUE TITLE
App doesn't have an icon

### ISSUE THREAD

**Issue by noClaps** [aritra-tech/KeepIt#2]
![Screenshot_20221007-185649~2](https://user-images.githubusercontent.com/103803129/194620364-4ec067ee-a139-4c1e-9bc5-c9b17b750fc0.png)

**Comment by binayshaw7777** [comment]
I want to work on this issue!

**Comment by aritra-tech** [comment]
Yeah sure @binayshaw7777

**Comment by SuyogMahajan** [comment]
Hey, I want to work with this one !!

**Comment by aritra-tech** [comment]
> Hey, I want to work with this one !!

Sorry @SuyogMahajan, but @binayshaw7777 is working on this issue as he commented first, there are other issues and you can also create your own issue

**Comment by HawkItzme** [comment]
Hey, @aritra-tech what's the update of this issue? Ig it's still not fixed , can you assign it to me

**Comment by binayshaw7777** [comment]
> Hey, @aritra-tech what's the update of this issue? Ig it's still not fixed , can you assign it to me

Hey, sorry. I couldn't use my computer due to electric issues in my town, which also resulted in the same. I completed the design, just having branch issues. This is why it's taking time.
