### ISSUE TITLE
Markdown and reminders support

### ISSUE THREAD

**Issue by noClaps** [aritra-tech/KeepIt#3]
Is it possible to add support for GitHub Flavored Markdown? This would allow for things like lists and checklists and general text formatting, without needing to create a separate note type. You don't have to add support for stuff like LaTeX or Mermaid diagrams if you don't want to.

Adding on to that, reminders/deadlines would be quite good for stuff like checklists, or even just regular notes.

**Comment by aritra-tech** [comment]
Yeah, @noClaps that's a nice idea

**Comment by aritra-tech** [comment]
So, I am assigning you

**Comment by noClaps** [comment]
I don't know programming, I'm just saying that from a user perspective

**Comment by aritra-tech** [comment]
> I don't know programming, I'm just saying that from a user perspective

Ooo ok ok 
Thanks, @noClaps for your suggestion

**Comment by venkey-dev** [comment]
can you describe about this issue

**Comment by aritra-tech** [comment]
> can you describe about this issue

That's not an issue it's an idea if you read the first comment you will understand.

**Comment by venkey-dev** [comment]
So we need to integrate markdown in the app right

**Comment by aritra-tech** [comment]
> So we need to integrate markdown in the app right

Not needed right now
