### ISSUE TITLE
Recording feature 

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/KeepIt#6]
Users can add his/her voice recording in the notes.

There is a button in the **BottomSheet** called  **Recording** that's where you have to implement the code so that the user can add his/her voice along with the text

**Comment by neil0504** [comment]
Hey @aritra-tech , i would like to work on this issue.

**Comment by aritra-tech** [comment]
Sure @neil0504

**Comment by neil0504** [comment]
Hey @aritra-tech , I have added the code to store the recorded mp3 voice file in storage. What else is required ?

**Comment by aritra-tech** [comment]
> Hey @aritra-tech , I have added the code to store the recorded mp3 voice file in storage. What else is required ?

Nice work @neil0504 
You can now create a PR.

**Comment by neil0504** [comment]
Hey @aritra-tech , Check out the PR
