### ISSUE TITLE
create note view is not scrollable

### ISSUE THREAD

**Issue by HeyRonak** [aritra-tech/KeepIt#8]
Hello @aritra-tech , i have found issue in main page 

If user enters a long text then view is not scrollable.

![WhatsApp Image 2022-10-13 at 9 45 19 PM](https://user-images.githubusercontent.com/54742102/195651171-9fd77a21-6a5c-4867-8e55-976a1eac522f.jpeg)

i'm interested to work on this issue 
can you please assign me ?

**Comment by aritra-tech** [comment]
> Hello @aritra-tech , i have found issue in main page
> 
> If user enters a long text then view is not scrollable.
> 
> ![WhatsApp Image 2022-10-13 at 9 45 19 PM](https://user-images.githubusercontent.com/54742102/195651171-9fd77a21-6a5c-4867-8e55-976a1eac522f.jpeg)
> 
> i'm interested to work on this issue can you please assign me ?

Sure @ronakparmar533 
All the best
